---
name: Yak Build
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.gh*'    

jobs:
  build-win:
    strategy:
      matrix:
        os: [ 'windows' ]
    runs-on: ${{ matrix.os }}

    name: Yak Build & Publish
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Restore Packages
        run: nuget restore Crash.sln
  
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0
            7.0
              
      - name: Build Crash
        run: dotnet build Crash.sln --configuration Release

      - name: Build Yak Package
        run: |
          $config = "Release"
          $in = Resolve-Path("src\Crash\bin\$config\net48")
          $out = $in
          .\scripts\YakCompiler.ps1 -Path $in -DestinationPath $out -Config Release
        shell: powershell

      - id: yak
        uses: crashcloud/yak-publish@main
        with:
          package-name: 'Crash'
          token: ${{ secrets.YAK_TOKEN }}
          build-path: 'src/project/bin/**/x64/'
          publish: 'test'
